### ISSUE TITLE
Noob issues maybe - how to run?

### ISSUE THREAD

**Issue by g4njawizard** [jaylex32/Syncra#3]
Hi,
thank you very much for sharing your project. I was looking for a long time for such a feature.
Unfortunately I am not a coder and have my trouble starting it.
I tried:
```
(.venv) odin@mjolnir2:~/git/python/Syncra-main/src|⇒  python3 -m Syncra
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/odin/git/python/Syncra-main/src/Syncra/__init__.py", line 1, in <module>
    from .Syncra import main
ModuleNotFoundError: No module named 'Syncra.Syncra'
```
Whats the correct way to start your tool?
Kind regards

**Comment by estreetco** [comment]
You need to download and launch the .exe program. Go here and download the zip file which is 117mb:

https://github.com/jaylex32/Syncra/releases/tag/v1.6.5

**Comment by deafmute1** [comment]
The pyproject doesn't have entrypoints set up, and if you run init.py like this the relative import won't resolve properly.

Just run `python3 src/Syncra/main.py`. The init.py doesn't do anything except import the main function there.

**Comment by jaylex32** [comment]
there's now 3 versions, Windows, macOS, Linux, if you guys have this Oses please test them and let me know if they work.
